# Generated by Django 5.2 on 2025-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
